### ISSUE TITLE
[BUG] Browser hangs after closing last window in a workspace

### ISSUE THREAD

**Issue by mingfang** [Glue42/core#235]
Start with a workspace that has one window in it.
Close the window, and the workspace will close along with it.
After the workspace closes, the browser hangs completely.
The console contains this error message

```
export.js:15 Uncaught (in promise) Error: Could find workspace to remove with id wsFp45hAN7
    at st.removeWorkspace (export.js:15)
    at Object.checkForEmptyWorkspace (export.js:15)
    at Object.<anonymous> (export.js:15)
    at Generator.next (<anonymous>)
    at export.js:15
    at new Promise (<anonymous>)
    at R (export.js:15)
    at export.js:15
    at export.js:15
    at Array.forEach (<anonymous>)
    at Object.execute (export.js:15)
    at rt.raiseEvent (export.js:15)
    at Object.<anonymous> (export.js:15)
    at n.LayoutManager.emit (export.js:15)
    at n.controls.Tab._onCloseClick (export.js:15)
    at HTMLDivElement.dispatch (export.js:40)
    at HTMLDivElement.g.handle (export.js:40)
```

**Comment by mingfang** [comment]
To see this problem you will need to start with two workspaces.
If only one workspace, somehow the "Untitled 1" workspaces "feature" hides this problem.

**Comment by mingfang** [comment]
it looks like any controller side "exceptions" will cause the browser to hang.
unfortunately this causes a really bad user experience and is a blocker for me to move forward.

**Comment by flashd2n** [comment]
Hey @mingfang we were not able to reproduce with error, so I suggest that you update your packages to the latest versions. We were also not able to cause the browser to hang in any way. 

However, if your workspaces frame app is a React app (which I believe is the case for you) and you run it in dev mode and an uncaught error or unhandled promise rejection happens, then React intercepts it, the app becomes unresponsive and you end up with a React error page. This is not the case with a prod build and it just how React handles stuff by default.

However, going over the steps you described we saw a different unhandled promise rejection , which causes the effect I described above. We will fix that ASAP and link the PR here.

**Comment by mingfang** [comment]
@flashd2n 
I confirmed that the hanging behavior was caused by React in dev mode, and that it does not hang in production mode.
This is huge relief. Thanks for pointing it out.

**Comment by mingfang** [comment]
@flashd2n
This problem is not entirely fixed.
Now I'm about to close the last workspace.
After closing, a new "untitled" workspaces is automatically created, expected behavior.
But I can crash the app by closing that newly created workspace very quickly.
Usually I have to do it 4 or 5 times to cause the crash.
Here is the error

```
Uncaught (in promise) Error: Internal Workspaces Communication Error. Attempted operation: {"operation":"getWorkspaceSnapshot","domain":"workspaces","data":{"itemId":"1H6Hyjve-"}}.  -> Inner message: The platform rejected operation getWorkspaceSnapshot for domain: workspaces with reason: "Cannot find frame for item: 1H6Hyjve-"
    at Bridge.<anonymous> (static/js/1.chunk.js:72337)
    at Generator.throw (<anonymous>)
    at rejected (static/js/1.chunk.js:70465)
```
