### ISSUE TITLE
[BUG] while using workspaces, calling getBounds on a frame throws an exception when `window.screenX` is a negative number.

### ISSUE THREAD

**Issue by HristoKolev** [Glue42/core#294]
When I try to call `wps.getBounds()` when the browser window is partially out of bounds in the left part of the screen I get an error.

![Capture](https://user-images.githubusercontent.com/13748164/150381351-544ccc7c-5f4e-4053-b694-7c66f6526f72.PNG)

**Comment by flashd2n** [comment]
Hi, yeah the validation does not take into account negative, aka out of screen bounds. Will address this is ASAP.
