### ISSUE TITLE
[BUG] Adding react-app-rewired to CRA 5 app crashes the app

### ISSUE THREAD

**Issue by nareshbhatia** [Glue42/core#332]
**Describe the bug**
The React tutorial instructs to install `react-app-wired@2.1.5` to a freshly created CRA app. However after doing this with the latest CRA (version 5), the app crashes at runtime.

**To Reproduce**
1. Create a new app using CRA 5: `npx create-react-app my-app`
2. Add suggested dependencies: `npm install --save @glue42/react-hooks bootstrap@4.4.1 react-app-rewired@2.1.5`
3. Change package.json as instructed

```
"start": "react-app-rewired start --scripts-version react-scripts",
"build": "react-app-rewired build --scripts-version react-scripts",
"test": "react-app-rewired test --scripts-version react-scripts",
```
4. Copy config-overrides.js from the tutorial project. Here are the contents:

```
const path = require("path");

module.exports = function override(config) {
    config.resolve.alias = {
        react: path.resolve(__dirname, "node_modules/react"),
        "react-dom": path.resolve(__dirname, "node_modules/react-dom")
    };

    return config;
};
```

5. Now run the app: `npm start`
6. App crashes with the following errors:

![CleanShot 2022-02-25 at 00 34 14](https://user-images.githubusercontent.com/1220198/155660128-b0bf9b41-3f1a-4980-83a0-d454259ca33b.png)

**Expected behavior**
App should not crash.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 98.0.4758.102

**Smartphone (please complete the following information):**
 N/A

**Additional context**
- What is the purpose of adding react-app-rewired to a Glue42 React project? Can this dependency be removed?
- I don't see a similar instruction in the Glue42 Enterprise docs.

**Comment by flashd2n** [comment]
Hi @nareshbhatia We investigated the issue and it is caused by a broken backwards compatibility between the latest CRA and the react and react-dom aliases which we have defined with react-app-rewired. All of the @glue42 packages remain fully functional with the latest React. We are bundling a few fixes and improvements to the React tutorial into a PR, which should be ready in a few days. Thanks for reaching out!

**Comment by nareshbhatia** [comment]
Thanks, @flashd2n. Could you please explain why do you need the use of react-app-wired to configure webpack. It would be ideal if we don't have to tinker with default create-react-app.

- Could this requirement be avoided by moving to other popular builders like vite?
- Do you support typescript (e.g. the create-react-app typescript template)?

**Comment by nareshbhatia** [comment]
Thank you @flashd2n. I will start creating my apps using my preferred templates and start integrating with Glue42.
