### ISSUE TITLE
[BUG] Can't retrieve glue instance with `useContext(GlueContext)` when the application is ejected into a window.

### ISSUE THREAD

**Issue by AN1BRA** [Glue42/core#356]
**Describe the bug**
Can't retrieve glue instance with `useContext(GlueContext)` when the application is ejected into a window.

**To Reproduce**
1. Add a sample App (in this case React) that gets the glue instance and logs it in console
```javascript
export default () => {
  const glue = useContext(GlueContext);
  console.log(glue);
  
  return (
    <>
    </>
  );
}
```
3. Go to Workspaces App
4. Open the application within the workspaces app, works fine and glue instance is retrieved correctly
![glue1](https://user-images.githubusercontent.com/42269554/159298904-fce47acd-8a5d-44b7-b396-b4563f13a2e9.png)
5. Click the `Eject` icon to open the app in a new browser window
6. See error:
 - glue instance is now null in the sample App
 - Workspaces App throws the following exception:
```
Uncaught (in promise) Error: Internal Platform Communication Error. Attempted operation: "applicationStart" with data: {"name":"test","waitForAGMReady":true}.  -> Inner message: The platform rejected operation applicationStart for domain: appManager with reason: "Application start for test timed out waiting for client to initialize Glue"
```
![glue2](https://user-images.githubusercontent.com/42269554/159299241-bab8aec5-db9c-4a7d-b4e3-610fd5af7b37.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu Focal Fossa]
 - Browser [Chrome]
 - Version [98.0.4758.102]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]

**Additional context**

**Comment by flashd2n** [comment]
Hi @AN1BRA This is not a known issue and I was not able to reproduce it. I tried with a simple vanilla JS client and a freshly built CRA app. Both worked as expected when added to a workspace and ejected from the workspace.

I would like to help you sort this out, but for that I would need a reproducible project. Can you please give me a repo with a project that reproduces the issue, I would like to see what the set up is, what the workspace frame is, how the client is being initialized and so on.
