### ISSUE TITLE
How to add new application to a workspace while we have a maximized window?

### ISSUE THREAD

**Issue by HristoKolev** [Glue42/core#404]
If I maximize a window in a workspace and then try to add a new application through the workspace API I get this error:

![image](https://user-images.githubusercontent.com/13748164/172163295-6ba149d6-4668-4cb8-b656-4a1174d11326.png)

If I try to add an application through the menu - nothing happens and I get the same error but this time as a warning:

![image](https://user-images.githubusercontent.com/13748164/172163550-647241a8-e738-4469-abee-0bc8cdea35ac.png)

The question is, how do I add windows to a workspace when it has a maximized window?

**Comment by SvetozarMateev** [comment]
Unfortunately this isn't supported at the moment and your only option is to restore the maximized window before adding the new application.
