### ISSUE TITLE
Add README to the NPM packages

### ISSUE THREAD

**Issue by petyosi** [Glue42/core#48]
The [NPM package pages for @glue42](https://www.npmjs.com/package/@glue42/cli-core) are empty - this is taken from the README inside the package.

**Describe the solution you'd like**
We can either copy the main README to each package or provide a short README that explains the specifics of the package.

**Comment by kirilpopov** [comment]
This is valid for:
* [@glue42/cli](https://www.npmjs.com/package/@glue42/clu)
* [@glue42/web](https://www.npmjs.com/package/@glue42/web)
* [@glue42/gateway-ws](https://www.npmjs.com/package/@glue42/gateway-ws)
