### ISSUE TITLE
[BUG] Stocks app from tutorial doesn't start correctly with Glue42 being always unavailable

### ISSUE THREAD

**Issue by arpanoid** [Glue42/core#547]
**Describe the bug**
.Currently, I am following through with the [Glue42 Core tutorial](https://core-docs.glue42.com/tutorials/javascript/index.html#2_project_setup). and I am stuck at step 3.1 

After setting up the main Clients app and the Stocks app, when I run the command `await glue.windows.open("stocks", "http://localhost:9100/").catch(console.error);` , it throws the following error in the Stocks app.
![image](https://user-images.githubusercontent.com/36093287/201826635-e6b27d15-1fbf-426d-8b3e-8c368b4f186d.png)

**To Reproduce**
Follow the [Glue42 Core javascript tutorial](https://core-docs.glue42.com/tutorials/javascript/index.html) till 3.1.

**Comment by flashd2n** [comment]
Hi @arpanoid thanks for reaching out! Unfortunately our JS tutorial is using an old version of the Glue42 Web lib, which had an unintended breaking change introduced with V2.6.0, which was resolved with V2.6.2. We will update all Glue42 packages in the JS tutorial and the issue will be resolved.
