### ISSUE TITLE
[BUG] React Tutorial -> Window Context example is missing object property reference.

### ISSUE THREAD

**Issue by arpanoid** [Glue42/core#561]
**Describe the bug**
Under the window context section, Stocks details are empty because the property reference is missing. 

React Tutorial -> Window Context example is missing object property reference. It should reference ` windowContext?.symbol` instead of just ` windowContext`. 

Happy to create PR if you're accepting the contributions.

**Screenshots**
![image](https://user-images.githubusercontent.com/36093287/203133716-9642a240-1ad3-49e3-a5b3-6eaa425e6124.png)

**Comment by arpanoid** [comment]
Not an issue.

**Comment by flashd2n** [comment]
Hey @arpanoid just want to throw out there that all contributions are welcome :)
