### ISSUE TITLE
[BUG] Glue42 core workspaces fail when you try to open quickly more then n number of workspace with several windows inside

### ISSUE THREAD

**Issue by stoil** [Glue42/core#563]
**Describe the bug**
When you start spawning (await glue.workspaces.restoreWorkspace(layoutName, options)) new workspaces with several application windows in each, at some point after the 8th workspace, glue will throw an error and from that point onward the interopabbility and communication as a whole between the web platform and the workspace window is not working (eg. you can not spawn more workspaces). It happens both locally and when deployed in production environment.

**To Reproduce**
1. Create a main application which uses workspace
2. Define a bunch of static layouts with a few application windows in each and pass the layouts to the webPlatform -> config->layouts->local property
3. Load the main application and click on the + button next to the workspace tab
4. Start adding new workspaces
5. See error

**Expected behavior**
I would expect that glue should be able to spawn as many workspace window as the user wants without breaking.

**Screenshots**
This is the error in the browser devtools console. after glue breaks.
![image](https://user-images.githubusercontent.com/5312835/203559821-19b25d86-de92-4bdf-8481-2dcebb512696.png)

**Desktop (please complete the following information):**
 - OS: Windos 10
 - Browser: Chrome
 - Version: 107.0.5304.107 (Official Build) (32-bit) 

**Glue packages versions**
 - @glue42/desktop: 5.14.5
 - @glue42/react-hooks: 2.7.1
 - @glue42/web: 2.7.1
 - @glue42/web-gns: 0.4.1
 - @glue42/web-platform: 1.13.1
 - @glue42/workspaces-api: 1.16.0
 - @glue42/workspaces-ui-react: 1.10.1

**Additional context**
In our setup we have a main workspace which holds the main app (the web platform) and we have a bunch of other client apps. Also we have several different workspace layouts which are statically defined. Users can open a new workspace and load a predefined layout as usual by clicking on the + button. From this new layout user can click on some ui components within the application windows inside of the workspace and this will call an interop registered in the platform. The interop itself will simply spawn a new workspace and load  one of the predefined layouts. Problem is the same even if you start spawning new workspaces the standard way by clicking on the + button and then clicking on the list of available workspace layouts.

**Comment by flashd2n** [comment]
Hey @stoil we managed to reproduce the issue, found the problem and will publish fixes ASAP.
