### ISSUE TITLE
[BUG] Subscribing to contexts sometimes replays the current context data and sometimes it doesn`t

### ISSUE THREAD

**Issue by Indeavr** [Glue42/core#63]
```
glue.contexts.subscribe("testContext", (data) => {
    // it should be called one time when subsribing with data = last update
})
```

If for example "app1" makes an update to "testContext" then subscribes for the same context the last data send will not be replayed, because the "updater" of the context is the one "subscribing"

Steps to reproduce:
1. `glue.contexts.update("testContext", {test: "value"})`
2. `glue.contexts.subscribe("testContext", (data) => {
        // not called
    })`

But if you call "update" (step 1) from another app (app2) and then subsribe from app1 it works.

The replay should happen always.

**Comment by petyosi** [comment]
@flashd2n - what's the status of this issue? Is it invalid, fixed somehow?

**Comment by Indeavr** [comment]
The issue was Invalid.
