### ISSUE TITLE
[BUG] Workspace restore after hibernation does not restore window context

### ISSUE THREAD

**Issue by stoil** [Glue42/core#708]
**Describe the bug**
When you resume a workspace after being hibernated, the window context for the windows inside the workspace does not get restored which leads to problems.

**To Reproduce**

1. Setup a basic Glue Core project
2. Configure the web platform and the client application
3. Activate the workspace hibernation 
Use configuration similar to this:

```
const config = {
    workspaces: {
        hibernation: {
            maximumActiveWorkspaces: {
                threshold: 2
            },
            idleWorkspaces: {
                idleMSThreshold: 60000
            }
        }
    },
    glue: {...},
    layouts: {...}
};
```
4. Add a few simple workspace layouts (provide some static context which will be passed as window context to the respective application windows)
5. Open 3 workspace layouts (no matter if you use the same workspace layout or not)
6. Click on the first workspace tab which should have been hibernated based on the hibernation config
7. Examine if the window context is restored to the state which was provided in the Layout definition

**Expected behavior**
When workspace is resumed after being hibernated, window context for each application window within the workspace should be restored to the state before the hibernation.

**Desktop:**
 - OS: Windos 10
 - Browser: Chrome
 - Version: 107.0.5304.107 (Official Build) (32-bit)

**Glue packages versions:**
 - @glue42/react-hooks: 2.18.1
 -  @glue42/web: 2.18.1
 -  @glue42/web-gns: 0.4.1
 -  @glue42/web-platform: 1.23.1
 -  @glue42/workspaces-api: 1.20.2
 - @glue42/workspaces-ui-react: 2.4.3

**Comment by flashd2n** [comment]
Hi @stoil Thank for reporting this issue, I was able to reproduce and implemented a fix with #707
