### ISSUE TITLE
[BUG] Error thrown when calling `addContextListener` from an iframe

### ISSUE THREAD

**Issue by fdore** [Glue42/core#711]
**Describe the bug**

We have a web platform loading apps inside iframes. 
When an app is calling `addContextListener`, the following error is thrown:

```
this.glue.windows.my(...).getContext is not a function
    at GlueController.getContextForMyWindow (fdc3.umd.js:1109:43)
    at ChannelsController.<anonymous> (fdc3.umd.js:2391:65)
    at Generator.next (<anonymous>)
    at fdc3.umd.js:40:75
    at new Promise (<anonymous>)
    at __awaiter (fdc3.umd.js:36:16)
    at ChannelsController.handleWindowContextOnOpening (fdc3.umd.js:2390:20)
    at ChannelsController.<anonymous> (fdc3.umd.js:2167:26)
    at Generator.next (<anonymous>)
    at fulfilled (fdc3.umd.js:37:62)
```

Note the error also occurs when subsequently calling `joinUserChannel`.

**To Reproduce**

With `addContextListener`

1. Create a glue enabled app, and call `addContextListener` on fdc3 ready
2. Create a web platform, and add an iframe pointing to the app created at step 1

With `joinUserChannel`

1. Create a glue enabled app, call `addContextListener` on fdc3 ready and add a button to call `joinUserChannel`
2. Create a web platform, and add an iframe pointing to the app created at step 1
3. Click on the button to join user channel

**Expected behavior**

No error should be thrown

**Code Sample**

[Here is a sample project reproducing the issue](https://codesandbox.io/s/zen-sanne-o18os0?file=/index.html)

**Desktop (please complete the following information):**
* Glue Version: 
    * @glue42/web-platform@**1.24.3**
    * @glue42/web@**2.19.1**
    *  @glue42/fdc3@**3.2.0**
* OS: MacOS 11.2.3
* Browser Chrome (Version 112)

**Additional context**

**Comment by ksgeorgieva** [comment]
Hi, @fdore. 
Thank you for reporting the issue. I was able to replicate the bug. We're working on a fix.
