### ISSUE TITLE
[BUG] broadcast message not received in specific scenario 

### ISSUE THREAD

**Issue by fdore** [Glue42/core#717]
**Describe the bug**

We have noticed an issue where an app doesn’t receive a broadcast message in the specific scenario described below:

**To Reproduce**

1. Create an app which does the following
    1. Join user channel  (eg. Channel 1)
    2. Register a context listener 
    3. Join another user channel (eg. Channel 2)
2. Render two instances of the app inside iframes within a web platform
3. Broadcast a message from the first app

**Expected behavior**
The second app should receive the context. 

**Actual behavior**
The second app doesn’t receive the context.

Note the issue doesn’t occur with the following versions
@glue42/fdc3: 3.0.1
@glue42/web: 2.11.1
@glue42/web-platform: 1.18.1

**Screenshots**
[Here is a link reproducing the issue.](https://codesandbox.io/s/frosty-tree-9cq4f3?file=/app/index.html)
(You'll need to preview outside of CodeSandbox)

**Desktop (please complete the following information):**
- OS: Mac 13.3.1
- Chrome 112
- Packages
@glue42/fdc3: 3.2.1
@glue42/web: 2.20.0
@glue42/web-platform: 1.25.0

**Comment by ksgeorgieva** [comment]
Hi @fdorem, 
Thank for reporting the bug. I was able to reproduce it and a fix is on its way.
