### ISSUE TITLE
[BUG] The channels object is undefined.

### ISSUE THREAD

**Issue by ghost** [Glue42/core#94]
We have updated our Glue42 Core library to version 1.1.2.

Below is our glue.config.json file.

![glue-config](https://user-images.githubusercontent.com/22574133/85469210-f884ab00-b5df-11ea-9e4a-f44d148c7ac4.png)

But when we call window.glue.channels, it is undefined. Below is the window.glue object.

![window-glue](https://user-images.githubusercontent.com/22574133/85469429-384b9280-b5e0-11ea-9a5a-3dd91fbb5f15.jpg)

**Comment by flashd2n** [comment]
Hello @rpmanago 

Thank you for your interest in Glue42 Core and for reaching out!

Inside the [Channels Capabilities selection](https://docs.glue42.com/core/capabilities/channels/index.html#initialization) you can find details on how to initialize channels inside of your application.

The problem you are facing is that inside of `glue.config.json` you need to pass the channel definitions (name, meta and optionally data).

Then, inside of your application when calling the `GlueWeb `factory function you need to pass `channels: true` for the Channels API to be initialized.

Please don't hesitate to contact us if you need any additional help.
